// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace QuantConnect.Algorithm.CSharp.ChinaTrade.MLnet;
public  class SampleRegression
{
    /// <summary>
    /// model input class for SampleRegression.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(1)]
        [ColumnName(@"Lable")]
        public float Lable { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"PreviousMinuteKLineReturn3")]
        public float PreviousMinuteKLineReturn3 { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"OpenReturn")]
        public float OpenReturn { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"PreviousMinuteKLineReturn2")]
        public float PreviousMinuteKLineReturn2 { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"PreviousMinuteKLineReturn1")]
        public float PreviousMinuteKLineReturn1 { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"MinuteKLineReturn")]
        public float MinuteKLineReturn { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"MinuteKLineReturnFromPreviousClose")]
        public float MinuteKLineReturnFromPreviousClose { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"MinutePriceBreakout")]
        public float MinutePriceBreakout { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"MinutePriceBreakoutEma")]
        public float MinutePriceBreakoutEma { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for SampleRegression.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Lable")]
        public float Lable { get; set; }

        [ColumnName(@"PreviousMinuteKLineReturn3")]
        public float PreviousMinuteKLineReturn3 { get; set; }

        [ColumnName(@"OpenReturn")]
        public float OpenReturn { get; set; }

        [ColumnName(@"PreviousMinuteKLineReturn2")]
        public float PreviousMinuteKLineReturn2 { get; set; }

        [ColumnName(@"PreviousMinuteKLineReturn1")]
        public float PreviousMinuteKLineReturn1 { get; set; }

        [ColumnName(@"MinuteKLineReturn")]
        public float MinuteKLineReturn { get; set; }

        [ColumnName(@"MinuteKLineReturnFromPreviousClose")]
        public float MinuteKLineReturnFromPreviousClose { get; set; }

        [ColumnName(@"MinutePriceBreakout")]
        public float MinutePriceBreakout { get; set; }

        [ColumnName(@"MinutePriceBreakoutEma")]
        public float MinutePriceBreakoutEma { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion
}